In [8]:
#KMean with KNN
import pandas as pd
import numpy as np
import scipy as sc
import matplotlib.pyplot as ml


pw = pd.read_csv('C:\\Users\\Dell-pc\\Desktop\\Data science ML DL python\\Practice\\Dataset\\data set important\\TestCricket.csv')
df=pd.DataFrame(pw)
df
df['HS'] = df['HS'].map(lambda x: x.rstrip('*'))
df['id']=np.arange(92)

area_dict = dict(zip(df['id'], df['Player']))


del df['Player']
del df['id']

cols = df.columns
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce', axis=1)

df.fillna(df.mean()).dropna(axis=1, how='all')


#dataframe is now can be used with supervised algorithm
x=df
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 10))
x = scaler.fit_transform(x)




In [9]:

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=0).fit(x)
y=kmeans.labels_

from sklearn import cross_validation, neighbors
clf = neighbors.KNeighborsClassifier()
clf = neighbors.KNeighborsClassifier()
clf.fit(x, y)
accuracy = clf.score(x,y)


In [30]:
from sklearn import cross_validation, neighbors
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score



bestI=1000000000000
bestK=0
I=[]
for i in range(2,int(x.size/100)+16):
    kmeans = KMeans(n_clusters=i, random_state=0).fit(x)
    
    inertia=kmeans.inertia_//100
    I.append(inertia)
    if bestI>inertia:
        bestI=inertia
        bestK=i
print(bestK)
bestI
I




22


[19.0,
 15.0,
 12.0,
 11.0,
 10.0,
 9.0,
 8.0,
 7.0,
 7.0,
 7.0,
 6.0,
 6.0,
 6.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 4.0,
 4.0,
 3.0,
 3.0]

4


In [12]:
df

Mat   Inns    NO     Runs     HS    Ave   100    50     0  class
0   200.0  329.0  33.0  15921.0  248.0  53.78  51.0  68.0  14.0      0
1   168.0  287.0  29.0  13378.0  257.0  51.85  41.0  62.0  17.0      0
2   166.0  280.0  40.0  13289.0  224.0  55.37  45.0  58.0  16.0      0
3   164.0  286.0  32.0  13288.0  270.0  52.31  36.0  63.0   8.0      0
4   134.0  233.0  17.0  12400.0  319.0  57.40  38.0  52.0  11.0      3
5   131.0  232.0   6.0  11953.0  400.0  52.88  34.0  48.0  17.0      3
6   164.0  280.0  49.0  11867.0  203.0  51.37  30.0  66.0  15.0      0
7   149.0  252.0  15.0  11814.0  374.0  49.84  34.0  50.0  15.0      3
8   147.0  266.0  15.0  11629.0  294.0  46.33  31.0  55.0   8.0      3
9   156.0  265.0  44.0  11174.0  205.0  50.56  27.0  63.0  11.0      0
10  168.0  260.0  46.0  10927.0  200.0  51.06  32.0  50.0  22.0      0
11  125.0  214.0  16.0  10122.0  236.0  51.12  34.0  45.0  12.0      3
12  118.0  213.0  19.0  10099.0  313.0  52.05  34.0  33.0  19.0      3
13  117.0  205.0  13.0   9265.0  277.0  48.25  27.0  38.0  11.0      3
14  118.0  215.0   6.0   8900.0  333.0  42.58  20.0  46.0  13.0      3
15  124.0  189.0  21.0   8832.0  280.0  52.57  23.0  43.0   6.0      3
16  120.0  200.0  22.0   8830.0  329.0  49.60  25.0  46.0  15.0      3
17  134.0  225.0  34.0   8781.0  281.0  45.97  17.0  56.0  14.0      3
18  115.0  198.0  22.0   8643.0  329.0  49.10  28.0  27.0   9.0      3
19  103.0  184.0  14.0   8625.0  380.0  50.73  30.0  29.0  14.0      3
20  104.0  180.0   6.0   8586.0  319.0  49.34  23.0  32.0  16.0      3
21  121.0  182.0  12.0   8540.0  291.0  50.23  24.0  45.0  10.0      3
22  133.0  235.0  21.0   8463.0  190.0  39.54  15.0  45.0  14.0      1
23  107.0  183.0  14.0   8281.0  311.0  49.00  26.0  35.0  10.0      3
24  117.0  204.0  18.0   8231.0  215.0  44.25  18.0  39.0   7.0      1
25  104.0  181.0   8.0   8181.0  227.0  47.28  23.0  35.0  10.0      1
26  108.0  193.0  23.0   8114.0  246.0  47.72  22.0  42.0  10.0      3
27  106.0  176.0  16.0   8074.0  278.0  50.46  21.0  39.0   7.0      3
28   93.0  160.0  21.0   8032.0  365.0  57.78  26.0  30.0  12.0      3
29  128.0  209.0  17.0   8029.0  153.0  41.81  20.0  47.0  19.0      1
..    ...    ...   ...      ...    ...    ...   ...   ...   ...    ...
62   86.0  146.0  12.0   5949.0  194.0  44.39  16.0  27.0   8.0      2
63   87.0  154.0   8.0   5842.0  291.0  40.01  15.0  31.0  12.0      1
64   76.0  143.0  10.0   5825.0  219.0  43.79  14.0  29.0  12.0      1
65   78.0  131.0  15.0   5807.0  278.0  50.06  17.0  28.0  10.0      2
66  103.0  154.0  22.0   5768.0  237.0  43.69  15.0  29.0  12.0      1
67   96.0  171.0  16.0   5764.0  207.0  37.18  14.0  33.0  14.0      1
68  102.0  173.0  15.0   5762.0  233.0  36.46  13.0  27.0  13.0      1
69   82.0  147.0   9.0   5719.0  197.0  41.44  18.0  18.0   9.0      2
70   66.0  123.0   4.0   5705.0  253.0  47.94  20.0  24.0   6.0      2
71   96.0  137.0  20.0   5570.0  204.0  47.60  17.0  26.0  14.0      1
72  147.0  206.0  24.0   5515.0  125.0  30.30   5.0  35.0  17.0      1
73   90.0  156.0  15.0   5502.0  249.0  39.02  16.0  17.0  22.0      1
74   87.0  145.0  11.0   5492.0  193.0  40.98  16.0  23.0  14.0      1
75   81.0  132.0  20.0   5462.0  231.0  48.76  14.0  30.0  11.0      1
76   77.0  131.0  11.0   5444.0  299.0  45.36  17.0  18.0   9.0      2
77   61.0  102.0   7.0   5410.0  211.0  56.94  15.0  28.0   4.0      2
78   56.0  104.0  14.0   5370.0  215.0  59.66  20.0  21.0   4.0      2
79   74.0  125.0  14.0   5357.0  250.0  48.26  15.0  33.0   4.0      2
80   75.0  136.0  10.0   5345.0  196.0  42.42  14.0  26.0  11.0      1
81   82.0  148.0   7.0   5334.0  185.0  37.82  12.0  23.0   7.0      2
82   60.0  110.0  11.0   5323.0  254.0  53.76  13.0  32.0   3.0      2
83   74.0  131.0   7.0   5312.0  219.0  42.83  14.0  21.0   9.0      2
84  131.0  184.0  15.0   5248.0  163.0  31.05   8.0  27.0  16.0      1
85   67.0  123.0  12.0   5234.0  210.0  47.15  13.0  27.0   6.0      2
86   75.0  132.0  20.0   5222.

0.97826086956521741

In [ ]:
# Kmean with Other "classifcation" Technique

In [14]:
from sklearn.cluster import KMeans
def GetKFromNB( i,x ):
    kmeans = KMeans(n_clusters=i, random_state=0).fit(x)
    cl =kmeans.labels_
    y=cl
    nb = GaussianNB()
    yNB =nb.fit(x, y).predict(x)
    accuracy =accuracy_score(y, yNB)
    return accuracy

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

bestAcc=0
bestK=0
for i in range(3,int(x.size/100)):
    acc=GetKFromNB(i,x)
    if bestAcc<acc:
        bestAcc=acc
        bestK=i
print (bestK)
kmeans = KMeans(n_clusters=bestK ,random_state=0).fit(x)
df['class']= kmeans.labels_

7


7


In [20]:
df['Player']=area_dict.values()
df

Mat   Inns    NO     Runs     HS    Ave   100    50     0  class  \
0   200.0  329.0  33.0  15921.0  248.0  53.78  51.0  68.0  14.0      3   
1   168.0  287.0  29.0  13378.0  257.0  51.85  41.0  62.0  17.0      3   
2   166.0  280.0  40.0  13289.0  224.0  55.37  45.0  58.0  16.0      3   
3   164.0  286.0  32.0  13288.0  270.0  52.31  36.0  63.0   8.0      3   
4   134.0  233.0  17.0  12400.0  319.0  57.40  38.0  52.0  11.0      5   
5   131.0  232.0   6.0  11953.0  400.0  52.88  34.0  48.0  17.0      5   
6   164.0  280.0  49.0  11867.0  203.0  51.37  30.0  66.0  15.0      3   
7   149.0  252.0  15.0  11814.0  374.0  49.84  34.0  50.0  15.0      5   
8   147.0  266.0  15.0  11629.0  294.0  46.33  31.0  55.0   8.0      5   
9   156.0  265.0  44.0  11174.0  205.0  50.56  27.0  63.0  11.0      3   
10  168.0  260.0  46.0  10927.0  200.0  51.06  32.0  50.0  22.0      3   
11  125.0  214.0  16.0  10122.0  236.0  51.12  34.0  45.0  12.0      5   
12  118.0  213.0  19.0  10099.0  313.0  52.05  34.0  33.0  19.0      5   
13  117.0  205.0  13.0   9265.0  277.0  48.25  27.0  38.0  11.0      4   
14  118.0  215.0   6.0   8900.0  333.0  42.58  20.0  46.0  13.0      0   
15  124.0  189.0  21.0   8832.0  280.0  52.57  23.0  43.0   6.0      4   
16  120.0  200.0  22.0   8830.0  329.0  49.60  25.0  46.0  15.0      5   
17  134.0  225.0  34.0   8781.0  281.0  45.97  17.0  56.0  14.0      2   
18  115.0  198.0  22.0   8643.0  329.0  49.10  28.0  27.0   9.0      4   
19  103.0  184.0  14.0   8625.0  380.0  50.73  30.0  29.0  14.0      0   
20  104.0  180.0   6.0   8586.0  319.0  49.34  23.0  32.0  16.0      0   
21  121.0  182.0  12.0   8540.0  291.0  50.23  24.0  45.0  10.0      4   
22  133.0  235.0  21.0   8463.0  190.0  39.54  15.0  45.0  14.0      2   
23  107.0  183.0  14.0   8281.0  311.0  49.00  26.0  35.0  10.0      4   
24  117.0  204.0  18.0   8231.0  215.0  44.25  18.0  39.0   7.0      4   
25  104.0  181.0   8.0   8181.0  227.0  47.28  23.0  35.0  10.0      4   
26  108.0  193.0  23.0   8114.0  246.0  47.72  22.0  42.0  10.0      4   
27  106.0  176.0  16.0   8074.0  278.0  50.46  21.0  39.0   7.0      4   
28   93.0  160.0  21.0   8032.0  365.0  57.78  26.0  30.0  12.0      0   
29  128.0  209.0  17.0   8029.0  153.0  41.81  20.0  47.0  19.0      2   
..    ...    ...   ...      ...    ...    ...   ...   ...   ...    ...   
62   86.0  146.0  12.0   5949.0  194.0  44.39  16.0  27.0   8.0      6   
63   87.0  154.0   8.0   5842.0  291.0  40.01  15.0  31.0  12.0      6   
64   76.0  143.0  10.0   5825.0  219.0  43.79  14.0  29.0  12.0      6   
65   78.0  131.0  15.0   5807.0  278.0  50.06  17.0  28.0  10.0      1   
66  103.0  154.0  22.0   5768.0  237.0  43.69  15.0  29.0  12.0      6   
67   96.0  171.0  16.0   5764.0  207.0  37.18  14.0  33.0  14.0      6   
68  102.0  173.0  15.0   5762.0  233.0  36.46  13.0  27.0  13.0      6   
69   82.0  147.0   9.0   5719.0  197.0  41.44  18.0  18.0   9.0      6   
70   66.0  123.0   4.0   5705.0  253.0  47.94  20.0  24.0   6.0      1   
71   96.0  137.0  20.0   5570.0  204.0  47.60  17.0  26.0  14.0      6   
72  147.0  206.0  24.0   5515.0  125.0  30.30   5.0  35.0  17.0      2   
73   90.0  156.0  15.0   5502.0  249.0  39.02  16.0  17.0  22.0      6   
74   87.0  145.0  11.0   5492.0  193.0  40.98  16.0  23.0  14.0      6   
75   81.0  132.0  20.0   5462.0  231.0  48.76  14.0  30.0  11.0      6   
76   77.0  131.0  11.0   5444.0  299.0  45.36  17.0  18.0   9.0      1   
77   61.0  102.0   7.0   5410.0  211.0  56.94  15.0  28.0   4.0      1   
78   56.0  104.0  14.0   5370.0  215.0  59.66  20.0  21.0   4.0      1   
79   74.0  125.0  14.0   5357.0  250.0  48.26  15.0  33.0   4.0      1   
80   75.0  136.0  10.0   5345.0  196.0  42.42  14.0  26.0  11.0      6   
81   82.0  148.0   7.0   5334.0  185.0  37.82  12.0  23.0   7.0      6   
82   60.0  110.0  11.0   5323.0  254.0  53.76  13.0  32.0   3.0      1   
83   74.0  131.0   7.0   5312.0  219.0  42.83  14.0  21.0   9.0      6   
84  131.0 

In [25]:
# get K  using Decision trees
from sklearn import tree
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
def GetKFromDT( i,x ):
    kmeans = KMeans(n_clusters=i, random_state=0).fit(x)
    cl =kmeans.labels_
    y=cl
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(x, y)
    YDT=clf.predict(x)
    accuracy =accuracy_score(y, YDT)
    return accuracy

bestAcc=0
bestK=0
for i in range(3,int(x.size/100)):
    acc=GetKFromDT(i,x)
    if bestAcc<acc:
        bestAcc=acc
        bestK=i
print (bestK)
print (acc)
kmeans = KMeans(n_clusters=bestK ,random_state=0).fit(x)
df['class']= kmeans.labels_

3
1.0


In [23]:
df['Player']=area_dict.values()
df

Mat   Inns    NO     Runs     HS    Ave   100    50     0  class  \
0   200.0  329.0  33.0  15921.0  248.0  53.78  51.0  68.0  14.0      2   
1   168.0  287.0  29.0  13378.0  257.0  51.85  41.0  62.0  17.0      2   
2   166.0  280.0  40.0  13289.0  224.0  55.37  45.0  58.0  16.0      2   
3   164.0  286.0  32.0  13288.0  270.0  52.31  36.0  63.0   8.0      2   
4   134.0  233.0  17.0  12400.0  319.0  57.40  38.0  52.0  11.0      2   
5   131.0  232.0   6.0  11953.0  400.0  52.88  34.0  48.0  17.0      2   
6   164.0  280.0  49.0  11867.0  203.0  51.37  30.0  66.0  15.0      2   
7   149.0  252.0  15.0  11814.0  374.0  49.84  34.0  50.0  15.0      2   
8   147.0  266.0  15.0  11629.0  294.0  46.33  31.0  55.0   8.0      2   
9   156.0  265.0  44.0  11174.0  205.0  50.56  27.0  63.0  11.0      2   
10  168.0  260.0  46.0  10927.0  200.0  51.06  32.0  50.0  22.0      2   
11  125.0  214.0  16.0  10122.0  236.0  51.12  34.0  45.0  12.0      1   
12  118.0  213.0  19.0  10099.0  313.0  52.05  34.0  33.0  19.0      1   
13  117.0  205.0  13.0   9265.0  277.0  48.25  27.0  38.0  11.0      1   
14  118.0  215.0   6.0   8900.0  333.0  42.58  20.0  46.0  13.0      0   
15  124.0  189.0  21.0   8832.0  280.0  52.57  23.0  43.0   6.0      1   
16  120.0  200.0  22.0   8830.0  329.0  49.60  25.0  46.0  15.0      1   
17  134.0  225.0  34.0   8781.0  281.0  45.97  17.0  56.0  14.0      2   
18  115.0  198.0  22.0   8643.0  329.0  49.10  28.0  27.0   9.0      1   
19  103.0  184.0  14.0   8625.0  380.0  50.73  30.0  29.0  14.0      0   
20  104.0  180.0   6.0   8586.0  319.0  49.34  23.0  32.0  16.0      0   
21  121.0  182.0  12.0   8540.0  291.0  50.23  24.0  45.0  10.0      1   
22  133.0  235.0  21.0   8463.0  190.0  39.54  15.0  45.0  14.0      1   
23  107.0  183.0  14.0   8281.0  311.0  49.00  26.0  35.0  10.0      1   
24  117.0  204.0  18.0   8231.0  215.0  44.25  18.0  39.0   7.0      1   
25  104.0  181.0   8.0   8181.0  227.0  47.28  23.0  35.0  10.0      1   
26  108.0  193.0  23.0   8114.0  246.0  47.72  22.0  42.0  10.0      1   
27  106.0  176.0  16.0   8074.0  278.0  50.46  21.0  39.0   7.0      1   
28   93.0  160.0  21.0   8032.0  365.0  57.78  26.0  30.0  12.0      0   
29  128.0  209.0  17.0   8029.0  153.0  41.81  20.0  47.0  19.0      1   
..    ...    ...   ...      ...    ...    ...   ...   ...   ...    ...   
62   86.0  146.0  12.0   5949.0  194.0  44.39  16.0  27.0   8.0      1   
63   87.0  154.0   8.0   5842.0  291.0  40.01  15.0  31.0  12.0      1   
64   76.0  143.0  10.0   5825.0  219.0  43.79  14.0  29.0  12.0      1   
65   78.0  131.0  15.0   5807.0  278.0  50.06  17.0  28.0  10.0      0   
66  103.0  154.0  22.0   5768.0  237.0  43.69  15.0  29.0  12.0      1   
67   96.0  171.0  16.0   5764.0  207.0  37.18  14.0  33.0  14.0      1   
68  102.0  173.0  15.0   5762.0  233.0  36.46  13.0  27.0  13.0      1   
69   82.0  147.0   9.0   5719.0  197.0  41.44  18.0  18.0   9.0      1   
70   66.0  123.0   4.0   5705.0  253.0  47.94  20.0  24.0   6.0      0   
71   96.0  137.0  20.0   5570.0  204.0  47.60  17.0  26.0  14.0      1   
72  147.0  206.0  24.0   5515.0  125.0  30.30   5.0  35.0  17.0      1   
73   90.0  156.0  15.0   5502.0  249.0  39.02  16.0  17.0  22.0      1   
74   87.0  145.0  11.0   5492.0  193.0  40.98  16.0  23.0  14.0      1   
75   81.0  132.0  20.0   5462.0  231.0  48.76  14.0  30.0  11.0      1   
76   77.0  131.0  11.0   5444.0  299.0  45.36  17.0  18.0   9.0      0   
77   61.0  102.0   7.0   5410.0  211.0  56.94  15.0  28.0   4.0      0   
78   56.0  104.0  14.0   5370.0  215.0  59.66  20.0  21.0   4.0      0   
79   74.0  125.0  14.0   5357.0  250.0  48.26  15.0  33.0   4.0      0   
80   75.0  136.0  10.0   5345.0  196.0  42.42  14.0  26.0  11.0      1   
81   82.0  148.0   7.0   5334.0  185.0  37.82  12.0  23.0   7.0      1   
82   60.0  110.0  11.0   5323.0  254.0  53.76  13.0  32.0   3.0      0   
83   74.0  131.0   7.0   5312.0  219.0  42.83  14.0  21.0   9.0      1   
84  131.0 

In [ ]:
##GradientBoostingClassifier
##measure  accuracy  for variation in parameters


In [ ]:
import pandas as pd
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

df=pd.read_excel('C:\\Users\\Dell-pc\\Desktop\\Data science ML DL\\Practice\\Dataset\\data set important\\titanic.xls')
df.head()

for c in df.columns:
    df[c]=df[c].apply(str)
    le=preprocessing.LabelEncoder().fit(df[c])
    df[c] =le.transform(df[c])
    

y=df['survived']
x=df.loc[0:, df.columns != 'survived'] 
#Import Library 
from sklearn.ensemble import GradientBoostingClassifier 
#Assumed you have, X (predictor) and Y (target) for
#training data set and x_test(predictor) of test_dataset #Create Gradient Boosting Classifier object 
model= GradientBoostingClassifier(n_estimators=10,learning_rate=1, max_depth=1, random_state=0) 
#Train the model using the training sets and check score 
model.fit(x, y) 
#Predict Output 
predicted= model.predict(x)

accuracy =accuracy_score(y, predicted)
accuracy*100

# accuracy decrease when increase in learning rate for same max_depth and  number of estimators
#accuracy increase when decrease in learning rate for same max_depth and  number of estimators

#accuracy remain almost same when increase in n_estimators  for same max_depth and number of estimators
#accuracy decrease when decrease in n_estimators  for same max_depth and number of estimators

#accuracy increase when increase in max_depth for same n_estimators and  learning rate
#accuracy decrease when decrease in max_depth for same n_estimators and  learning rate






In [ ]:
#WHICH classification Algorithm can be used for regression


# mixed Data

In [9]:
import pandas as pd
import numpy as np

In [39]:
df=pd.DataFrame()
df['numericalData']=np.random.randint(11,111)
df['CategoricalData']=['Male','Female','gay','lesb']*25
df['OrdinalVariable']=['small','medium','large','extraLarge','XXL']*20
df['interleaved']=['first','third','fifth','seven']*25

In [40]:
df['numericalData']=[np.random.randint(11,1111) for i in range(100)]
df['survived']=[0,1]*50
df.head()

numericalData CategoricalData OrdinalVariable interleaved  survived
0           1017            Male           small       first         0
1            366          Female          medium       third         1
2            410             gay           large       fifth         0
3             19            lesb      extraLarge       seven         1
4            606            Male             XXL       first         0

In [48]:
Y=df['survived']
X=df.loc[0:, df.columns != 'survived']


# problem categorical data, ordinal,interleaved 

In [ ]:
# categorical data may cause problem in KNN or K mean same for ordinal and interleaved 
#if not conevrted into number intelegently

In [ ]:
#converting categorical to numeric

In [46]:
# all data
from sklearn import preprocessing
for c in df.columns:
    le=preprocessing.LabelEncoder().fit(df[c])
    df[c] =le.transform(df[c])


In [47]:
df.head()

numericalData  CategoricalData  OrdinalVariable  interleaved  survived
0             82                1                4            1         0
1             25                0                3            3         1
2             31                2                2            0         0
3              0                3                1            2         1
4             45                1                0            1         0

In [31]:
>>> from sklearn.preprocessing import OneHotEncoder
>>> enc = OneHotEncoder()
>>> enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  

>>> enc.n_values_


>>> enc.transform([[0, 1, 1]]).toarray()


array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]])

In [32]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
['cold']


In [35]:
for c in df.columns:
    
    df[c] =enc.fit_transform(df[c])

C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Anaconda\lib\site-packages\skle

In [36]:
df

numericalData  \
0     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
1     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
2     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
3     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
4     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
5     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
6     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
7     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
8     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
9     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
10    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
11    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
12    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
13    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
14    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
15    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
16    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
17    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
18    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
19    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
20    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
21    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
22    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
23    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
24    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
25    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
26    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
27    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
28    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
29    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
..                                                ...   
70    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
71    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
72    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
73    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
74    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
75    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
76    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
77    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
78    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
79    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
80    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
81    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
82    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
83    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
84    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
85    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
86    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
87    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
88    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
89    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
90    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
91    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
92    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
93    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
94    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
95    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
96    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
97    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
98    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
99    (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   

                                      CategoricalData  \
0     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
1     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
2     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
3     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
4     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
5     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
6     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.0...   
7     (0, 99)\t1.0\n  (0, 98)\t1.0\n  (0, 97)\t1.

In [49]:
#DecisionTreeClassifier
>>> from sklearn import tree

>>> clf = tree.DecisionTreeClassifier()
>>> clf = clf.fit(X, Y)

>>> clf.predict(X)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

# Handeling with these data

# Handeling Missing values